sudo: required
services:
  - docker

before_install:
  - docker build -t maxalmonte14/docker-react -f Dockerfile.dev .

script:
#  - docker run maxalmonte14/docker-react npm run test -- --coverage
  - echo "OK" # Jest don't want to run without watching, so let's fake it